POST http://localhost:80/message/post
Content-Type: application/json

{
  "ToUserName": "oie",
  "FromUserName": "jofwaejo",
  "Content": "写一篇200字关于上海的文章",
  "CreateTime": 313
}

###

# curl https://api.openai.com/v1/completions
#  -H 'Content-Type: application/json'
#  -H 'Authorization: Bearer YOUR_API_KEY'
#  -d '{
#  "model": "text-davinci-003",
#  "prompt": "Say this is a test",
#  "max_tokens": 7,
#  "temperature": 0
#}'
POST https://api.openai.com/v1/completions
Authorization: Bearer YOUR_API_KEY
Content-Type: application/json

{
  "model": "text-davinci-003",
  "prompt": "Say this is a test",
  "max_tokens": 7,
  "temperature": 0
}

###

